### ISSUE TITLE
Does not build with libremidi 4.5.0, nor 5.4.3

### ISSUE THREAD

**Issue by matthiasbeyer** [nhielost/obs-midi-mg#194]
Hi

I am trying to package this for nixpkgs, but it does not build with libremidi 4.5.0 (current in nixpkgs) or 5.4.3 (to be updated to in nixpkgs, but this breaks advanced-scene-switcher, so its currently on hold).

I am not a CPP person, so I don't know how to investigate further.

Build output:

```
obs-midi-mg> /build/source/src/mmg-config.cpp: In member function 'void MMGConfig::load(const QString&)':
obs-midi-mg> /build/source/src/mmg-config.cpp:75:18: error: ignoring return value of 'virtual bool QFile::open(QIODeviceBase::OpenMode)', declared with attribute 'nodiscard' [-Werror=unused-result]
obs-midi-mg>    75 |         file.open(QFile::ReadOnly | QFile::Text);
obs-midi-mg>       |         ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
obs-midi-mg> In file included from /nix/store/9lf2mfhsk7s379mfsh8nqc4xabdg6dw6-qtbase-6.10.2/include/QtCore/qdir.h:11,
obs-midi-mg>                  from /nix/store/9lf2mfhsk7s379mfsh8nqc4xabdg6dw6-qtbase-6.10.2/include/QtCore/QDir:1,
obs-midi-mg>                  from /build/source/src/actions/../obs-midi-mg.h:22,
obs-midi-mg>                  from /build/source/src/actions/../mmg-string.h:19,
obs-midi-mg>                  from /build/source/src/actions/../mmg-json.h:22,
obs-midi-mg>                  from /build/source/src/actions/../mmg-mapping.h:22,
obs-midi-mg>                  from /build/source/src/actions/mmg-action.h:22,
obs-midi-mg>                  from /build/source/src/mmg-binding.h:22,
obs-midi-mg>                  from /build/source/src/mmg-config.h:22,
obs-midi-mg>                  from /build/source/src/mmg-config.cpp:19:
obs-midi-mg> /nix/store/9lf2mfhsk7s379mfsh8nqc4xabdg6dw6-qtbase-6.10.2/include/QtCore/qfile.h:291:32: note: declared here
obs-midi-mg>   291 |     QFILE_MAYBE_NODISCARD bool open(OpenMode flags) override;
obs-midi-mg>       |                                ^~~~
obs-midi-mg> /build/source/src/mmg-config.cpp: In member function 'void MMGConfig::save(const QString&) const':
obs-midi-mg> /build/source/src/mmg-config.cpp:142:18: error: ignoring return value of 'virtual bool QFile::open(QIODeviceBase::OpenMode)', declared with attribute 'nodiscard' [-Werror=unused-result]
obs-midi-mg>   142 |         file.open(QFile::WriteOnly | QFile::Text | QFile::Truncate);
obs-midi-mg>       |         ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
obs-midi-mg> /nix/store/9lf2mfhsk7s379mfsh8nqc4xabdg6dw6-qtbase-6.10.2/include/QtCore/qfile.h:291:32: note: declared here
obs-midi-mg>   291 |     QFILE_MAYBE_NODISCARD bool open(OpenMode flags) override;
obs-midi-mg>       |   


obs-midi-mg> cc1plus: all warnings being treated as errors
obs-midi-mg> make[2]: *** [CMakeFiles/obs-midi-mg.dir/build.make:423: CMakeFiles/obs-midi-mg.dir/src/mmg-config.cpp.o] Error 1
obs-midi-mg> make[2]: *** Waiting for unfinished jobs....
obs-midi-mg> In file included from /nix/store/9lf2mfhsk7s379mfsh8nqc4xabdg6dw6-qtbase-6.10.2/include/QtCore/qstring.h:24,
obs-midi-mg>                  from /nix/store/9lf2mfhsk7s379mfsh8nqc4xabdg6dw6-qtbase-6.10.2/include/QtCore/qdir.h:9,
obs-midi-mg>                  from /nix/store/9lf2mfhsk7s379mfsh8nqc4xabdg6dw6-qtbase-6.10.2/include/QtCore/QDir:1,
obs-midi-mg>                  from /build/source/src/obs-midi-mg.h:22,
obs-midi-mg>                  from /build/source/src/mmg-string.h:19,
obs-midi-mg>                  from /build/source/src/mmg-json.h:22,
obs-midi-mg>                  from /build/source/src/mmg-preference.h:22,
obs-midi-mg>                  from /build/source/src/mmg-preference.cpp:19:
obs-midi-mg> /nix/store/9lf2mfhsk7s379mfsh8nqc4xabdg6dw6-qtbase-6.10.2/include/QtCore/qanystringview.h: In instantiation of 'constexpr QAnyStringView::QAnyStringView(Container&&, QtPrivate::wrapped_t<Container, QString>&&) [with Container = const MMGText&; typename std::enable_if<conjunction_v<std::negation<std::disjunction<std::is_same<typename std::remove_cvref<_Tp>::type, Tag>, std::is_same<typename std::remove_cvref<_Tp>::type, QAnyStringView>, std::is_pointer<typename std::decay<_Tp>::type>, std::disjunction<QtPrivate::IsCompatibleCharType<Char>, std::disjunction<std::is_same<typename std::remove_cvref<_Tp>::type, char8_t>, std::is_same<typename std::remove_cvref<_Tp>::type, char>, std::is_same<typename std::remove_cvref<_Tp>::type, unsigned char>, std::is_same<typename std::remove_cvref<_Tp>::type, signed char> > >, std::is_same<typename std::remove_cvref<_Tp>::type, QByteArray>, std::is_same<typename std::remove_cvref<_Tp>::type, QString> > >, std::is_convertible<Container, QString> >, bool>::type <anonymous> = true; QtPrivate::wrapped_t<Container, QString> = QString]':
obs-midi-mg> /nix/store/9lf2mfhsk7s379mfsh8nqc4xabdg6dw6-qtbase-6.10.2/include/QtCore/qstring.h:345:23:   required from 'QString QString::arg(const T&, int, QChar) const [with T = MMGText; typename std::enable_if<std::conjunction<std::negation<QtPrivate::treat_as_integral_arg<typename std::remove_cv< <template-parameter-1-1> >::type> >, std::is_convertible<T, QAnyStringView> >::value, bool>::type <anonymous> = true]'
obs-midi-mg>   345 |     { return arg_impl(QAnyStringView(a), fieldWidth, fillChar); }
obs-midi-mg>       |                       ^~~~~~~~~~~~~~~~~
obs-midi-mg> /build/source/src/mmg-preference.cpp:55:39:   required from here
obs-midi-mg>    55 |                 QString("[Preferences] <%1> %2").arg(MMGPreferences::availablePreferences()[id()]).arg(message));
obs-midi-mg>       |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
obs-midi-mg> /nix/store/9lf2mfhsk7s379mfsh8nqc4xabdg6dw6-qtbase-6.10.2/include/QtCore/qanystringview.h:220:35: error: ambiguous overload for 'operator=' (operand types are 'QtPrivate::wrapped_t<const MMGText&, QString>' {aka 'QString'} and 'const MMGText')
obs-midi-mg>   220 |         : QAnyStringView(capacity = std::forward<Container>(c)) {}
obs-midi-mg>       |                          ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
obs-midi-mg> /nix/store/9lf2mfhsk7s379mfsh8nqc4xabdg6dw6-qtbase-6.10.2/include/QtCore/qanystringview.h:220:35: note: there are 6 candidates
obs-midi-mg> /nix/store/9lf2mfhsk7s379mfsh8nqc4xabdg6dw6-qtbase-6.10.2/include/QtCore/qstring.h:226:14: note: candidate 1: 'QString& QString::operator=(const QString&)'
obs-midi-mg>   226 |     QString &operator=(const QString &) noexcept;
obs-midi-mg>       |              ^~~~~~~~
obs-midi-mg> In file included from /nix/store/9lf2mfhsk7s379mfsh8nqc4xabdg6dw6-qtbase-6.10.2/include/QtCore/qtdeprecationmarkers.h:8,
obs-midi-mg>                  from /nix/store/9lf2mfhsk7s379mfsh8nqc4xabdg6dw6-qtbase-6.10.2/include/QtCore/qtcoreexports.h:9,
obs-midi-mg>                  from /nix/store/9lf2mfhsk7s379mfsh8nqc4xabdg6dw6-qtbase-6.10.2/include/QtCore/qtcoreglobal.h:14,
obs-midi-mg>                  from /nix/store/9lf2mfhsk7s379mfsh8nqc4xabdg6dw6-qtbase-6.10.2/include/QtCore/qglobal.h:24,
obs-midi-mg>                  from /nix/store/9lf2mfhsk7s379mfsh8nqc4xabdg6dw6-qtbase-6.10.2/include/QtCore/qcompare.h:12,
obs-midi-mg>                  from /nix/store/9lf2mfhsk7s379mfsh8nqc4xabdg6dw6-qtbase-6.10.2/include/QtCore/qdir.h:8:
obs-midi-mg> /nix/store/9lf2mfhsk7s379mfsh8nqc4xabdg6dw6-qtbase-6.10.2/include/QtCore/qstring.h:230:5: note: candidate 2: 'QString& QString::operator=(QString&&)'
obs-midi-mg>   230 |     QT_MOVE_ASSIGNMENT_OPERATOR_IMPL_VIA_PURE_SWAP(QString)
obs-midi-mg>       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
obs-midi-mg> /nix/store/9lf2mfhsk7s379mfsh8nqc4xabdg6dw6-qtbase-6.10.2/include/QtCore/qstring.h:944:40: note: candidate 3: 'QString& QString::operator=(const char*)'
obs-midi-mg>   944 |     QT_ASCII_CAST_WARN inline QString &operator=(const char *ch)
obs-midi-mg>       |                                        ^~~~~~~~
obs-midi-mg> make[2]: *** [CMakeFiles/obs-midi-mg.dir/build.make:549: CMakeFiles/obs-midi-mg.dir/src/mmg-preference.cpp.o] Error 1
obs-midi-mg> make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/obs-midi-mg.dir/all] Error 2
obs-midi-mg> make: *** [Makefile:156: all] Error 2

```
